# -*- coding: utf-8 -*-
"""funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFl86u1Itu4kmgLnaVD2itkxh7NNWkhm
"""

import numpy as np
import math
import calendar

def sln_eqn(n):
  A = np.zeros((n,n))
  for i in range(n):
    for j in range(n):
      A[i][j] = float(input("A_ ="+str(i+1)+","+str(j+1)+"="))
  if np.linalg.det(A) == 0:
    print("El sistema no tiene solucion")
    X=[]
  else:
    B =np.zeros(n)
    for i in range(n):
      B[i] = float(input("B_"+str(i+1)+"="))
    X = np.linalg.solve(A,B)
    print("x = ",X)
    print("det(A) =" ,np.linalg.det(A))
    print("inv(A) =", np.linalg.inv(A))
  return X


def vectores(n):
  u = np.array([-1.2, -0.9, 0.56, 2 ])
  v = np.array([0.6, 0.3, 1.56, 3 ])
  print('Vector u = ',u)
  n = 4 #Este es el tamaño del vector, cantidad de elementos
  s = 0 #Se inicia la variable suma en 0
  for i in range(4):
    s = s+u[i]
    print('u = ',u[i])
  print('Suma  = ',s)

  for i in range(0,21,2):
    print('i = ',i+1)
  # Vamos hacer el producto punto enter u.v
  s = 0
  for i in range(4):
    s = s+u[i]*v[i]
  print('Producto punto u.v = ',s)
  return vectores


def elevar(x):
  y = x**2
  return y


def lista(n):
  lista =["manzana, banano, cereza"]
  lista_1 = list((5, -0.7,True))
  print('lista: ' , lista)
  print('lista _1:' , lista_1)
  for i  in range(len(lista)):
    print('lista pos_' +str(i+1)+':' , lista[i])
  lista.append("naranja")
  print('lista: ' , lista)
  return lista

def asignaturas(n):
  asignaturas = ["matematicas", "fisica", "quimica" , "historia","lenguaje"]
  print("asignaturas =" ,asignaturas)
  for i in range(len(asignaturas)):
    print("yo estudio =" ,asignaturas[i])
  #ingrese su nota
  for i in range(len(asignaturas)):
    nota = input("nota " + asignaturas[i] + ":")
    print(asignaturas[i], nota)
  return asignaturas


def promedio(arreglo, n):
  suma = 0
  for i in range(n):
    suma = suma + arreglo[i]
  prom = suma/n
  return prom


def suma_raiz(n):
  n = int(input("Ingrese el valor de n: "))
  s = 0
  i = 0
  if n%2==0:
    while i<n/2:
      i = i+1
      s = s+i*2+1
      print("s =" ,s)
  else:
    while i<=n/2:
      i = i+1
      s = s+i*2+1
      r= math.sqrt(s)
  print("r =" ,r)


def ecuacion(n):
  print("Vamos a resolver la ecuacion cuadratica,ax2+bc+c=0")
  a=float(input('ingrese a:'))
  b=float(input('ingrese b:'))
  c=float(input('ingrese c:'))
  # Vamos a calcular el discriminante d= b^2+4*c*a
  d=b**2-4*a*c
  print("El discriminante es:" ,d)
  if d>0:
    #print("Las soluciones son reales diferentes")
    x1 = (-b+math.sqrt(d))/(2*a)
    x2 = (-b-math.sqrt(d))/(2*a)
    print("x1=",x1)
    print("x2=",x2)
  elif d==0:
       print('Dos soluciones iguales')
       x1 = -b/(2*a)
       print('x1 = ',x1)
       print('x2 = ',x1)
  else:
         # Este de lo contrario lo evalua d<0 ( discriminante negativo)
         x1 = (-b+pow(d,1/2))/(2*a)
         x2 = (-b-pow(d,1/2))/(2*a)
         print('x1 = ' ,x1)
         print('x2 = ',x2)
         return ecuacion
         #Fin

def conjetura(n):
  # vamos a poner un ciclo mientras para
  # garantizar n>0
  n= int(input("ingrese un numero entero positivo: "))
  while n<=0:
    n = int(input("ingrese un numero entero positivo: "))
  # En este seccion vamos a probar las condiciones para la conjetura de collatz
  while n!=1:
    if n%2==0:
      n = n/2
    else:
       n = 3*n+1
    print("n= ",n)


def area_triangulo(n):
  # vamos a calcular el area de un triangulo
  # usando la ecuacion de Heron A = sqrt(s*(s-a)*(s-b)*(s-c)*)
  a= float(input("ingrese el lado a:"))
  while a<=0:
    a= float(input("ingrese el lado a:"))
  b= float(input("ingrese el lado b:"))
  while b<=0:
    b= float(input("ingrese el lado b"))
  c= float(input("ingrese el lado c"))
  while c<=0:
    c= float(input("ingrese el lado c"))
  s = (a+b+c)/2
  #ecuacion de Heron
  A = math.sqrt(s*(s-a)*(s-b)*(s-c))
  print("Area = ", A)


def resta(n):
  # vamos a contar desde $n$ hasta $o$
  # garantizar que n>0
  n=int(input("ingrese n"))
  i= n
  while n<=0:
    n=int(input("ingrese un numero positivo"))
  while i!=0:
    i=i-1
    print("n= ", i)


def vector_fila(n):
  # Definamos una variable tipo vector fila
  vector_fila = np.array([1, 2, 3, 4, 5, 6])
  print(vector_fila)
  for i in range(len(vector_fila)):
      print('v_' + str(i+1) + ' = ' + str(vector_fila[i]))
  n = int(input('n ='))
  v = np.zeros(n)
  for i in range(n):
    v[i] = float (input('v_' + str(i+1) + '='))
  print('v =', v)


def vector_columna(n):
  # determinar el valor mayor de los elementos de un vector
  n = int(input("ingrese el valor de n"))
  v = np.zeros(n)
  i = 0
  for i in range(n):
    v[i] = float(input("ingrese el valor de v" + str(i+1) + ":"))
  for i in range(n):
    print("v" + str(i+1) + "=" + str(v[i]))

def lista_agregar(n):
  lista =[ 1,2,3,4,5,6,7,8,9,10]
  for i in range(1,11):
    print(lista[-i],end=',')
    lista.reverse()
    print('\n',lista)


def alfabeto(n):
  letras = ['a', 'b', ' c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',  'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
  for i in range(len(letras)-1,-1,-1):
    if i % 2 != 0:
      letras.pop(i-1)
  print(letras)
  return alfabeto


# Define la funcion g(x)
# (Asumiendo f(x) y g(x) estan ya definidas ffc0eff5)
def g(x):
  return math.exp(x) / 3

def punto_fijo(n):
  # otener el valor de interacion de punto fijo por el usuario
  try:
    initial_guess = float(input("Ingrese un valor inicial para la iteración de punto fijo: "))
  except ValueError:
    print("Entrada inválida. Por favor ingrese un número.")
    initial_guess = None

  if initial_guess is not None:
    x0 = initial_guess
    tolerance = 0.0001
    max_iterations = 100
    x1 = None
    print(f"Iteración 0: x = {x0}")

    for i in range(max_iterations):
      try:
        x1 = g(x0)
        print(f"Iteración {i+1}: x = {x1}")
        if abs(x1 - x0) < tolerance:
          print(f"\nConvergencia alcanzada después de {i+1} iteraciones.")
          print(f"El punto fijo aproximado es: {x1}")
          break
        x0 = x1
      except OverflowError:
        print(f"\nError: OverflowError at iteration {i+1}. The values are growing too large.")
        print("This might indicate that the fixed-point iteration is diverging.")
        print("Consider trying a different initial guess or a different method.")
        break # Exit the loop if overflow occurs
    else:
      print(f"\nNo se alcanzó la convergencia después de {max_iterations} iterations.")
      if x1 is not None:
          print(f"Último valor calculado: {x1}")
      return None


def maxdetres(n):
  a = float(input("ingrese el primer numero:"))
  b= float(input("ingrese el segundo numero:"))
  c = float(input("ingrese el tercer numero:"))
  print("el numero mayor es:")
  return max(a,b,c)


def suma_y_multiplicacion(n):
    lista = []
    while True:
        try:
            n_str = input("Ingrese un numero (o 'fin' para terminar):")
            if n_str.lower() == 'fin':
                break
            n = float(n_str)
            lista.append(n)
        except ValueError:
            print("Entrada inválida. Por favor ingrese un número o 'fin'.")
    if not lista:
        print("No se ingresaron números.")
        return
    suma_total = sum(lista)
    producto_total = 1
    for num in lista:
        producto_total *= num
    print("La suma de los numeros es:", suma_total)
    print("La multiplicacion de los numeros es:", producto_total)
    return suma_y_multiplicacion


def MCD(a, b):
    while b!=0:
        a, b = b, a % b
    return a

def MCM(a, b):
    return abs(a*b) // MCD(a, b)


def calendario(n):
   while True:
     try:
         año = int(input("ingrese el año:"))
         if año<0:
          print("ingrese un año valido")
         else:
            break
     except ValueError:
      print("ingrese un año valido")
   while True:
       try:
         mes = int(input("ingrese el mes:"))
         if mes<0 or mes>12:
          print("ingrese un mes valido")
         else:
            break
       except ValueError:
        print("ingrese un mes valido")
   print("calendario del mes solicitado")
   print(calendar.month(año,mes))


def area(r):
  a = math.pi*r**2
  return a

def volumen(r,h):
  v = area(r)*h
  return v

import funciones

while True:
    f = input("Ingrese el numero de la funcion que desee (1-20) o 'fin' para terminar:")
    if f.lower() == 'fin':
        break
    try:
        f = int(f)
        if 1 <= f <= 20:
            if f == 1:
                print("punto fijo")
                funciones.punto_fijo(1)
            elif f == 2:
                print("ecuacion")
                funciones.ecuacion(2)
            elif f == 3:
                print("conjetura")
                funciones.conjetura(3)
            elif f == 4:
                print("resta")
                funciones.resta(4)
            elif f == 5:
                print("vector fila")
                funciones.vector_fila(5)
            elif f == 6:
                print("vector columna")
                funciones.vector_columna(6)
            elif f == 7:
                print("lista agregar")
                funciones.lista_agregar(7)
            elif f == 8:
                print("alfabeto")
                funciones.alfabeto(8)
            elif f == 9:
                print("sln_eqn")
                funciones.sln_eqn(9)
            elif f == 10:
                print("lista")
                funciones.lista(10)
            elif f == 11:
                print("asignaturas")
                funciones.asignaturas(11)
            elif f == 12:
                print("promedio")
                funciones.promedio(12)
            elif f == 13:
                print("suma_raiz")
                funciones.suma_raiz(13)
            elif f == 14:
                print("elevar")
                funciones.elevar(14)
            elif f == 15:
                print("area_triangulo")
                funciones.area_triangulo(15)
            elif f == 16:
                print("maxdetres")
                funciones.maxdetres(16)
            elif f == 17:
                print("suma_y_multiplicacion")
                funciones.suma_y_multiplicacion(17)
            elif f == 18:
                print("MCD")
                a = float(input("Ingrese el primer numero para MCD: "))
                b = float(input("Ingrese el segundo numero para MCD: "))
                print("MCD =", funciones.MCD(a, b))
            elif f == 19:
                print("MCM")
                a = float(input("Ingrese el primer numero para MCM: "))
                b = float(input("Ingrese el segundo numero para MCM: "))
                print("MCM =", funciones.MCM(a, b))
            elif f == 20:
                print("calendario")
                funciones.calendario(20)
        else:
            print("Número de función inválido. Ingrese un número del 1 al 20.")
    except ValueError:
        print("Entrada inválida. Por favor ingrese un número del 1 al 20 o 'fin'.")

print("Programa terminado.")
